<?php
		//$loan_url['Chedai'] = urlencode('http://wx.iisun.net/chedai.php?C=Chedai&M=receiveCode');
		$loan_url['Fangdai'] = urlencode('http://wx.iisun.net/zitan/index.php?C=Fangdai&M=receiveCode');
		//潜在客户菜单样式,默认菜单
		$menu['Fangdai'] = array(
			array(
				'name'=>'紫檀',
				'sub_button'=>array(
					array(
						'type'=>'view',
						'name'=>'样板间',
						'url'=>"https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx195e0960c65caad9&redirect_uri={$loan_url['Fangdai']}&response_type=code&scope=snsapi_base&state=100#wechat_redirect"
					),
					array(
						'type'=>'view',
						'name'=>'户型图',
						'url'=>"https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx195e0960c65caad9&redirect_uri={$loan_url['Fangdai']}&response_type=code&scope=snsapi_base&state=101#wechat_redirect"
					),
					array(
						'type'=>'view',
						'name'=>'楼盘详情',
						'url'=>"https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx195e0960c65caad9&redirect_uri={$loan_url['Fangdai']}&response_type=code&scope=snsapi_base&state=102#wechat_redirect"
					),
					array(
						'type'=>'view',
						'name'=>'楼盘相册',
						'url'=>"https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx195e0960c65caad9&redirect_uri={$loan_url['Fangdai']}&response_type=code&scope=snsapi_base&state=103#wechat_redirect"
					)
				)
			),
			array(
				'name'=>'专属服务',
				'sub_button'=>array(
					array(
						'type'=>'view',
						'name'=>'我的消息',
						'url'=>"https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx195e0960c65caad9&redirect_uri={$loan_url['Fangdai']}&response_type=code&scope=snsapi_base&state=2#wechat_redirect"
					),
					array(
						'type'=>'view',
						'name'=>'联系销售',
						'url'=>"https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx195e0960c65caad9&redirect_uri={$loan_url['Fangdai']}&response_type=code&scope=snsapi_base&state=3#wechat_redirect"
					),
					array(
						'type'=>'view',
						'name'=>'预约看房',
						'url'=>"https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx195e0960c65caad9&redirect_uri={$loan_url['Fangdai']}&response_type=code&scope=snsapi_base&state=4#wechat_redirect"
					)
				)
			),
			array(
				'name'=>'我的',
				'sub_button'=>array(
					array(
						'type'=>'view',
						'name'=>'个人信息',
						'url'=>"https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx195e0960c65caad9&redirect_uri={$loan_url['Fangdai']}&response_type=code&scope=snsapi_base&state=5#wechat_redirect"
					),
				)
			)
		);

		//管理员菜单样式
		$condition_menu['admin'] = array(
				array(
					'name'=>'紫檀',
					'sub_button'=>array(
						array(
							'type'=>'view',
							'name'=>'样板间',
							'url'=>"https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx195e0960c65caad9&redirect_uri={$loan_url['Fangdai']}&response_type=code&scope=snsapi_base&state=100#wechat_redirect"
						),
						array(
							'type'=>'view',
							'name'=>'户型图',
							'url'=>"https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx195e0960c65caad9&redirect_uri={$loan_url['Fangdai']}&response_type=code&scope=snsapi_base&state=101#wechat_redirect"
						),
						array(
							'type'=>'view',
							'name'=>'楼盘详情',
							'url'=>"https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx195e0960c65caad9&redirect_uri={$loan_url['Fangdai']}&response_type=code&scope=snsapi_base&state=102#wechat_redirect"
						),
						array(
							'type'=>'view',
							'name'=>'楼盘相册',
							'url'=>"https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx195e0960c65caad9&redirect_uri={$loan_url['Fangdai']}&response_type=code&scope=snsapi_base&state=103#wechat_redirect"
						)
					)
				),
				array(
					'name'=>'销售管理',
					'sub_button'=>array(
						array(
							'type'=>'view',
							'name'=>'注册销售员',
							'url'=>"https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx195e0960c65caad9&redirect_uri={$loan_url['Fangdai']}&response_type=code&scope=snsapi_base&state=6#wechat_redirect"
						),
						array(
							'type'=>'view',
							'name'=>'销售员详情',
							'url'=>"https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx195e0960c65caad9&redirect_uri={$loan_url['Fangdai']}&response_type=code&scope=snsapi_base&state=7#wechat_redirect"
						),
						array(
							'type'=>'view',
							'name'=>'业绩统计',
							'url'=>"https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx195e0960c65caad9&redirect_uri={$loan_url['Fangdai']}&response_type=code&scope=snsapi_base&state=8#wechat_redirect"
						),
						array(
							'type'=>'view',
							'name'=>'信息推送',
							'url'=>"https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx195e0960c65caad9&redirect_uri={$loan_url['Fangdai']}&response_type=code&scope=snsapi_base&state=9#wechat_redirect"
						),
					)
				),
				array(
					'name'=>'客户管理',
					'sub_button'=>array(
						array(
							'type'=>'view',
							'name'=>'客户列表',
							'url'=>"https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx195e0960c65caad9&redirect_uri={$loan_url['Fangdai']}&response_type=code&scope=snsapi_base&state=10#wechat_redirect"
						),
						array(
							'type'=>'view',
							'name'=>'客户分析',
							'url'=>"https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx195e0960c65caad9&redirect_uri={$loan_url['Fangdai']}&response_type=code&scope=snsapi_base&state=11#wechat_redirect"
						)
					)
				),
			);


		//销售员菜单样式
		$condition_menu['sale'] = array(
				array(
					'name'=>'紫檀',
					'sub_button'=>array(
						array(
							'type'=>'view',
							'name'=>'样板间',
							'url'=>"https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx195e0960c65caad9&redirect_uri={$loan_url['Fangdai']}&response_type=code&scope=snsapi_base&state=100#wechat_redirect"
						),
						array(
							'type'=>'view',
							'name'=>'户型图',
							'url'=>"https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx195e0960c65caad9&redirect_uri={$loan_url['Fangdai']}&response_type=code&scope=snsapi_base&state=101#wechat_redirect"
						),
						array(
							'type'=>'view',
							'name'=>'楼盘详情',
							'url'=>"https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx195e0960c65caad9&redirect_uri={$loan_url['Fangdai']}&response_type=code&scope=snsapi_base&state=102#wechat_redirect"
						),
						array(
							'type'=>'view',
							'name'=>'楼盘相册',
							'url'=>"https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx195e0960c65caad9&redirect_uri={$loan_url['Fangdai']}&response_type=code&scope=snsapi_base&state=103#wechat_redirect"
						)
					)
				),
				array(
					'name'=>'客户管理',
					'sub_button'=>array(
						array(
							'type'=>'view',
							'name'=>'客户留言',
							'url'=>"https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx195e0960c65caad9&redirect_uri={$loan_url['Fangdai']}&response_type=code&scope=snsapi_base&state=12#wechat_redirect"
						),
						array(
							'type'=>'view',
							'name'=>'客户评价',
							'url'=>"https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx195e0960c65caad9&redirect_uri={$loan_url['Fangdai']}&response_type=code&scope=snsapi_base&state=13#wechat_redirect"
						),
						array(
							'type'=>'view',
							'name'=>'信息推送',
							'url'=>"https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx195e0960c65caad9&redirect_uri={$loan_url['Fangdai']}&response_type=code&scope=snsapi_base&state=14#wechat_redirect"
						),
						array(
							'type'=>'view',
							'name'=>'客户信息补全',
							'url'=>"https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx195e0960c65caad9&redirect_uri={$loan_url['Fangdai']}&response_type=code&scope=snsapi_base&state=15#wechat_redirect"
						),
					)
				),
				array(
					'name'=>'我的',
					'sub_button'=>array(
						array(
							'type'=>'view',
							'name'=>'我的二维码',
							'url'=>"https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx195e0960c65caad9&redirect_uri={$loan_url['Fangdai']}&response_type=code&scope=snsapi_base&state=16#wechat_redirect"
						),
						array(
							'type'=>'view',
							'name'=>'个人信息',
							'url'=>"https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx195e0960c65caad9&redirect_uri={$loan_url['Fangdai']}&response_type=code&scope=snsapi_base&state=17#wechat_redirect"
						),
						array(
							'type'=>'view',
							'name'=>'业绩分析',
							'url'=>"https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx195e0960c65caad9&redirect_uri={$loan_url['Fangdai']}&response_type=code&scope=snsapi_base&state=18#wechat_redirect"
						),
						array(
							'type'=>'view',
							'name'=>'我的消息',
							'url'=>"https://open.weixin.qq.com/connect/oauth2/authorize?appid=wx195e0960c65caad9&redirect_uri={$loan_url['Fangdai']}&response_type=code&scope=snsapi_base&state=19#wechat_redirect"
						),
					)
				),
			);

			//个性化菜单显示条件
			$matchrule = array(
					'sale'=>array('group_id'=>'111'),
					'admin'=>array('group_id'=>'110')
			); 